package service

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// TestSpriteBackfillCandidates 验证候选筛选 SQL 只挑出「已索引、未软删、
// duration_ms>0 的视频」这一类，纯 SQL 筛选，不 stat 不生成。
func TestSpriteBackfillCandidates(t *testing.T) {
	db := makeTestDB(t)

	// 入选：已索引视频，duration_ms>0。
	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1','/g/v1.mp4','video/mp4',6000,'indexed',0)`)
	require.NoError(t, err)

	// 不入选：软删视频（deleted_at 非空）。
	_, err = db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video,deleted_at)
		VALUES('v2','/g/v2.mp4','video/mp4',6000,'indexed',0,CURRENT_TIMESTAMP)`)
	require.NoError(t, err)

	// 不入选：图片。
	_, err = db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('p1','/g/p1.jpg','image/jpeg',0,'indexed',0)`)
	require.NoError(t, err)

	// 不入选：duration_ms=0 的视频。
	_, err = db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v3','/g/v3.mp4','video/mp4',0,'indexed',0)`)
	require.NoError(t, err)

	// 不入选：status='pending' 的视频。
	_, err = db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v4','/g/v4.mp4','video/mp4',6000,'pending',0)`)
	require.NoError(t, err)

	got, err := spriteBackfillCandidates(db)
	require.NoError(t, err)
	require.Len(t, got, 1)
	require.Equal(t, "v1", got[0].id)
	require.Equal(t, "/g/v1.mp4", got[0].filePath)
	require.Equal(t, int64(6000), got[0].durationMs)
}

// TestBackfillSpritesGeneratesAndIdempotent 对 fixture 视频跑一轮，断言
// sprite.jpg 与 preview.mp4 都生成；再跑第二轮，断言两者都幂等（文件
// mtime 不变，不重新生成）。
func TestBackfillSpritesGeneratesAndIdempotent(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)

	srcDir := t.TempDir()
	src := filepath.Join(srcDir, "v1.mp4")
	require.NoError(t, exec.Command("ffmpeg", "-hide_banner", "-loglevel", "error",
		"-f", "lavfi", "-i", "testsrc=duration=6:size=320x240:rate=25", "-y", src).Run())

	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0)`, src)
	require.NoError(t, err)

	ix.BackfillSprites(context.Background())

	spritePath := filepath.Join(thumbDir, "v1", "sprite.jpg")
	fi1, err := os.Stat(spritePath)
	require.NoError(t, err, "sprite should be generated by the first backfill run")

	previewPath := filepath.Join(thumbDir, "v1", "preview.mp4")
	fp1, err := os.Stat(previewPath)
	require.NoError(t, err, "preview.mp4 should be generated by the first backfill run")

	ix.BackfillSprites(context.Background())
	fi2, err := os.Stat(spritePath)
	require.NoError(t, err)
	require.Equal(t, fi1.ModTime(), fi2.ModTime(), "second run must be idempotent (no re-generation)")

	fp2, err := os.Stat(previewPath)
	require.NoError(t, err)
	require.Equal(t, fp1.ModTime(), fp2.ModTime(), "preview second run must be idempotent (no re-generation)")
}

// TestBackfillSpritesCASReentrant 并发两次调用 BackfillSprites，断言不 panic
// 且不产生数据竞争（-race 兜底）；CAS 防重入下二者中至少一个应立即空转返回。
func TestBackfillSpritesCASReentrant(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)

	srcDir := t.TempDir()
	src := filepath.Join(srcDir, "v1.mp4")
	require.NoError(t, exec.Command("ffmpeg", "-hide_banner", "-loglevel", "error",
		"-f", "lavfi", "-i", "testsrc=duration=6:size=320x240:rate=25", "-y", src).Run())
	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0)`, src)
	require.NoError(t, err)

	done := make(chan struct{}, 2)
	for i := 0; i < 2; i++ {
		go func() {
			defer func() { done <- struct{}{} }()
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			ix.BackfillSprites(ctx)
		}()
	}
	<-done
	<-done

	spritePath := filepath.Join(thumbDir, "v1", "sprite.jpg")
	_, err = os.Stat(spritePath)
	require.NoError(t, err, "sprite should exist after concurrent backfill calls")

	previewPath := filepath.Join(thumbDir, "v1", "preview.mp4")
	_, err = os.Stat(previewPath)
	require.NoError(t, err, "preview.mp4 should exist after concurrent backfill calls")
}
