package service

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

// TestSpriteBackfillCandidates 验证候选筛选 SQL 只挑出「已索引、未软删、
// duration_ms>0 的视频」这一类，纯 SQL 筛选，不 stat 不生成。
func TestSpriteBackfillCandidates(t *testing.T) {
	db := makeTestDB(t)

	// 入选：已索引视频，duration_ms>0。
	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1','/g/v1.mp4','video/mp4',6000,'indexed',0)`)
	require.NoError(t, err)

	// 不入选：软删视频（deleted_at 非空）。
	_, err = db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video,deleted_at)
		VALUES('v2','/g/v2.mp4','video/mp4',6000,'indexed',0,CURRENT_TIMESTAMP)`)
	require.NoError(t, err)

	// 不入选：图片。
	_, err = db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('p1','/g/p1.jpg','image/jpeg',0,'indexed',0)`)
	require.NoError(t, err)

	// 不入选：duration_ms=0 的视频。
	_, err = db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v3','/g/v3.mp4','video/mp4',0,'indexed',0)`)
	require.NoError(t, err)

	// 不入选：status='pending' 的视频。
	_, err = db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v4','/g/v4.mp4','video/mp4',6000,'pending',0)`)
	require.NoError(t, err)

	got, err := spriteBackfillCandidates(db)
	require.NoError(t, err)
	require.Len(t, got, 1)
	require.Equal(t, "v1", got[0].id)
	require.Equal(t, "/g/v1.mp4", got[0].filePath)
	require.Equal(t, int64(6000), got[0].durationMs)
}

// TestBackfillSpritesGeneratesAndIdempotent 对 fixture 视频跑一轮，断言
// sprite.jpg 与 preview.mp4 都生成；再跑第二轮，断言两者都幂等（文件
// mtime 不变，不重新生成）。
func TestBackfillSpritesGeneratesAndIdempotent(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)
	ix.SetPreviewPregen(true) // 本测试专测 preview.mp4 补跑,需显式开启(默认纯懒生成)

	srcDir := t.TempDir()
	src := filepath.Join(srcDir, "v1.mp4")
	require.NoError(t, exec.Command("ffmpeg", "-hide_banner", "-loglevel", "error",
		"-f", "lavfi", "-i", "testsrc=duration=6:size=320x240:rate=25", "-y", src).Run())

	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0)`, src)
	require.NoError(t, err)

	ix.BackfillSprites(context.Background())

	spritePath := filepath.Join(thumbDir, "v1", "sprite.jpg")
	fi1, err := os.Stat(spritePath)
	require.NoError(t, err, "sprite should be generated by the first backfill run")

	previewPath := filepath.Join(thumbDir, "v1", "preview.mp4")
	fp1, err := os.Stat(previewPath)
	require.NoError(t, err, "preview.mp4 should be generated by the first backfill run")

	ix.BackfillSprites(context.Background())
	fi2, err := os.Stat(spritePath)
	require.NoError(t, err)
	require.Equal(t, fi1.ModTime(), fi2.ModTime(), "second run must be idempotent (no re-generation)")

	fp2, err := os.Stat(previewPath)
	require.NoError(t, err)
	require.Equal(t, fp1.ModTime(), fp2.ModTime(), "preview second run must be idempotent (no re-generation)")
}

// makeTestVideo 用 ffmpeg lavfi 生成一段固定时长的测试视频，供任务栏相关测试
// 复用（避免每个测试重复这段样板）。
func makeTestVideo(t *testing.T, dir, name string) string {
	t.Helper()
	src := filepath.Join(dir, name)
	require.NoError(t, exec.Command("ffmpeg", "-hide_banner", "-loglevel", "error",
		"-f", "lavfi", "-i", "testsrc=duration=6:size=320x240:rate=25", "-y", src).Run())
	return src
}

// TestBackfillSprites_AllReadyEmitsNoTask 覆盖 TDD 用例①:候选视频的 sprite/preview
// 都已就绪(无欠账)时，BackfillSprites 不应发出任何任务事件——即使注入了 registry。
func TestBackfillSprites_AllReadyEmitsNoTask(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)
	ix.SetPreviewPregen(true) // 本测试要求 preview.mp4 也纳入"无欠账"判定,需显式开启

	srcDir := t.TempDir()
	src := makeTestVideo(t, srcDir, "v1.mp4")
	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0)`, src)
	require.NoError(t, err)

	// 先跑一轮把 sprite/preview 都补齐，让候选处于"无欠账"状态。
	ix.BackfillSprites(context.Background())
	require.FileExists(t, filepath.Join(thumbDir, "v1", "sprite.jpg"))
	require.FileExists(t, filepath.Join(thumbDir, "v1", "preview.mp4"))

	var emitted []Task
	var mu sync.Mutex
	reg := NewTaskRegistry(func(tk Task) { mu.Lock(); emitted = append(emitted, tk); mu.Unlock() })
	ix.SetTaskRegistry(reg)

	ix.BackfillSprites(context.Background())

	mu.Lock()
	defer mu.Unlock()
	require.Empty(t, emitted, "候选全部已就绪时不应发出任何任务事件")
}

// TestBackfillSprites_PendingEmitsTaskWithRealProgress 覆盖 TDD 用例②:存在欠账
// 视频时应出现「生成视频预览」任务，label/type 正确，total=欠账数，current 随
// 处理推进到 total，终态 done。
func TestBackfillSprites_PendingEmitsTaskWithRealProgress(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)

	srcDir := t.TempDir()
	src1 := makeTestVideo(t, srcDir, "v1.mp4")
	src2 := makeTestVideo(t, srcDir, "v2.mp4")
	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0), ('v2',?,'video/mp4',6000,'indexed',0)`, src1, src2)
	require.NoError(t, err)

	var emitted []Task
	var mu sync.Mutex
	reg := NewTaskRegistry(func(tk Task) { mu.Lock(); emitted = append(emitted, tk); mu.Unlock() })
	ix.SetTaskRegistry(reg)

	ix.BackfillSprites(context.Background())

	mu.Lock()
	defer mu.Unlock()
	require.NotEmpty(t, emitted, "存在欠账视频时应发出任务事件")

	var sawDone bool
	var maxCurrent int64
	for _, e := range emitted {
		require.Equal(t, "preview-backfill", e.Type)
		require.Equal(t, "Generating video previews", e.Label)
		require.Equal(t, int64(2), e.Total, "total 应为欠账候选数(v1、v2 两条)")
		if e.Current > maxCurrent {
			maxCurrent = e.Current
		}
		if e.Status == "done" {
			sawDone = true
		}
	}
	require.True(t, sawDone, "应有 done 终态事件")
	require.Equal(t, int64(2), maxCurrent, "current 应随处理推进到 total")
}

// TestBackfillSprites_FfmpegMissingSetsErrorTask 覆盖 TDD 用例③:ffmpeg 不可用
// (PATH 置空模拟 exec.ErrNotFound)时，任务应带 TaskErrPreviewFfmpegMissing 错误终态。
func TestBackfillSprites_FfmpegMissingSetsErrorTask(t *testing.T) {
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)

	// 源文件本身只需通过第一层 os.Stat(源文件)检查，随后触发 ffmpeg 调用即可
	// 命中 exec.ErrNotFound,不要求是可解码的真实视频。
	src := filepath.Join(t.TempDir(), "v1.mp4")
	require.NoError(t, os.WriteFile(src, []byte("fake video bytes"), 0o644))
	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0)`, src)
	require.NoError(t, err)

	var emitted []Task
	var mu sync.Mutex
	reg := NewTaskRegistry(func(tk Task) { mu.Lock(); emitted = append(emitted, tk); mu.Unlock() })
	ix.SetTaskRegistry(reg)

	t.Setenv("PATH", "") // 模拟 ffmpeg 不可用：exec.Command 查不到可执行文件

	ix.BackfillSprites(context.Background())

	mu.Lock()
	defer mu.Unlock()
	var sawError bool
	for _, e := range emitted {
		if e.Status == "error" {
			sawError = true
			require.Equal(t, TaskErrPreviewFfmpegMissing, e.ErrorKey)
		}
	}
	require.True(t, sawError, "ffmpeg 不可用时应有 error 终态事件,带 TaskErrPreviewFfmpegMissing")
}

// TestBackfillSprites_NilRegistryDoesNotPanic 覆盖 TDD 用例④:未注入 registry 时
// BackfillSprites 必须照常工作，不 panic——回归既有全部 sprite/preview 测试路径。
func TestBackfillSprites_NilRegistryDoesNotPanic(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1) // 未调用 SetTaskRegistry，taskReg 保持 nil
	ix.SetPreviewPregen(true)                    // 本测试要求覆盖 preview.mp4 补跑路径,需显式开启

	srcDir := t.TempDir()
	src := makeTestVideo(t, srcDir, "v1.mp4")
	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0)`, src)
	require.NoError(t, err)

	require.NotPanics(t, func() { ix.BackfillSprites(context.Background()) })

	require.FileExists(t, filepath.Join(thumbDir, "v1", "sprite.jpg"))
	require.FileExists(t, filepath.Join(thumbDir, "v1", "preview.mp4"))
}

// TestBackfillSprites_PartialFailureStaysDone 覆盖裁决用例:3 条候选中仅 1 条
// 生成失败(损坏视频)时,任务终态应仍为 done、不带 errorKey,失败数只计入汇总
// 日志——对齐 BackfillOCR "只有全部候选都失败才 error" 的惯例,避免一条永久
// 损坏的视频每轮补跑都把任务栏刷成 Failed。
func TestBackfillSprites_PartialFailureStaysDone(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)

	srcDir := t.TempDir()
	src1 := makeTestVideo(t, srcDir, "v1.mp4")
	src2 := makeTestVideo(t, srcDir, "v2.mp4")
	// v3 是损坏视频(非法字节但文件存在):ffmpeg 能被找到,只是解码会失败,
	// 命中"个别失败"分支,而非 exec.ErrNotFound 触发的整轮放弃分支。
	src3 := filepath.Join(srcDir, "v3.mp4")
	require.NoError(t, os.WriteFile(src3, []byte("not a real video"), 0o644))

	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0), ('v2',?,'video/mp4',6000,'indexed',0), ('v3',?,'video/mp4',6000,'indexed',0)`,
		src1, src2, src3)
	require.NoError(t, err)

	obsCore, logs := observer.New(zap.InfoLevel)
	restore := zap.ReplaceGlobals(zap.New(obsCore))
	defer restore()

	var emitted []Task
	var mu sync.Mutex
	reg := NewTaskRegistry(func(tk Task) { mu.Lock(); emitted = append(emitted, tk); mu.Unlock() })
	ix.SetTaskRegistry(reg)

	ix.BackfillSprites(context.Background())

	mu.Lock()
	var final Task
	var sawFinal bool
	for _, e := range emitted {
		if e.Status == "done" || e.Status == "error" {
			final = e
			sawFinal = true
		}
	}
	mu.Unlock()

	require.True(t, sawFinal, "应有终态事件")
	require.Equal(t, "done", final.Status, "3 条候选仅 1 条失败,任务终态应仍为 done")
	require.Empty(t, final.ErrorKey, "部分失败不应携带 errorKey")

	var loggedFailed bool
	for _, entry := range logs.All() {
		if entry.Message != "sprite/preview 补跑完成" {
			continue
		}
		for _, f := range entry.Context {
			if f.Key == "failed" && f.Integer == 1 {
				loggedFailed = true
			}
		}
	}
	require.True(t, loggedFailed, "汇总日志应记录失败数=1")
}

// TestBackfillSprites_AllFailedSetsErrorTask 覆盖裁决用例:候选全部生成失败时,
// 任务终态应为 error 并携带 TaskErrPreviewPartialFailed——对齐 BackfillOCR
// "全部失败才 error"的惯例,而非出现任意失败就 error。
func TestBackfillSprites_AllFailedSetsErrorTask(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)

	srcDir := t.TempDir()
	src1 := filepath.Join(srcDir, "v1.mp4")
	src2 := filepath.Join(srcDir, "v2.mp4")
	require.NoError(t, os.WriteFile(src1, []byte("not a real video 1"), 0o644))
	require.NoError(t, os.WriteFile(src2, []byte("not a real video 2"), 0o644))

	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0), ('v2',?,'video/mp4',6000,'indexed',0)`, src1, src2)
	require.NoError(t, err)

	var emitted []Task
	var mu sync.Mutex
	reg := NewTaskRegistry(func(tk Task) { mu.Lock(); emitted = append(emitted, tk); mu.Unlock() })
	ix.SetTaskRegistry(reg)

	ix.BackfillSprites(context.Background())

	mu.Lock()
	defer mu.Unlock()

	var final Task
	var sawFinal bool
	for _, e := range emitted {
		if e.Status == "done" || e.Status == "error" {
			final = e
			sawFinal = true
		}
	}
	require.True(t, sawFinal, "应有终态事件")
	require.Equal(t, "error", final.Status, "候选全部失败时任务终态应为 error")
	require.Equal(t, TaskErrPreviewPartialFailed, final.ErrorKey)
	require.Equal(t, "2", final.ErrorParams["failed"])
}

// TestBackfillSpritesCASReentrant 并发两次调用 BackfillSprites，断言不 panic
// 且不产生数据竞争（-race 兜底）；CAS 防重入下二者中至少一个应立即空转返回。
func TestBackfillSpritesCASReentrant(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found")
	}
	db := makeTestDB(t)
	thumbDir := t.TempDir()
	ix := NewIndexer(db, &mockML{}, thumbDir, 1)
	ix.SetPreviewPregen(true) // 本测试要求覆盖 preview.mp4 补跑路径,需显式开启

	srcDir := t.TempDir()
	src := filepath.Join(srcDir, "v1.mp4")
	require.NoError(t, exec.Command("ffmpeg", "-hide_banner", "-loglevel", "error",
		"-f", "lavfi", "-i", "testsrc=duration=6:size=320x240:rate=25", "-y", src).Run())
	_, err := db.Exec(`INSERT INTO assets(id,file_path,mime_type,duration_ms,status,is_live_photo_video)
		VALUES('v1',?,'video/mp4',6000,'indexed',0)`, src)
	require.NoError(t, err)

	done := make(chan struct{}, 2)
	for i := 0; i < 2; i++ {
		go func() {
			defer func() { done <- struct{}{} }()
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			ix.BackfillSprites(ctx)
		}()
	}
	<-done
	<-done

	spritePath := filepath.Join(thumbDir, "v1", "sprite.jpg")
	_, err = os.Stat(spritePath)
	require.NoError(t, err, "sprite should exist after concurrent backfill calls")

	previewPath := filepath.Join(thumbDir, "v1", "preview.mp4")
	_, err = os.Stat(previewPath)
	require.NoError(t, err, "preview.mp4 should exist after concurrent backfill calls")
}
