// Package sqlite provides database initialization and helper utilities
// for NimoOS-Photos, including sqlite-vec vector table support.
package sqlite

import (
	"database/sql"
	"encoding/binary"
	"fmt"
	"math"
	"regexp"
	"strconv"
	"strings"

	sqlite_vec "github.com/asg017/sqlite-vec-go-bindings/cgo"
	_ "github.com/mattn/go-sqlite3" // CGO SQLite3 driver

	"github.com/NimoTech/NimoOS-Photos/common"
)

func init() {
	// Register the sqlite-vec extension so that vec0 virtual tables are available.
	sqlite_vec.Auto()
}

// maxOpenConns caps the shared pool. SQLite in WAL mode allows one writer
// plus concurrent readers; an unbounded database/sql pool just piles up
// connections (fd + memory) during indexing storms without adding write
// throughput. 8 covers the HTTP handlers plus every background worker
// (indexer x3, faces, embedder, schedulers) with headroom; nesting depth
// of query-inside-rows loops in this codebase is <= 2, far below the cap,
// so pool-exhaustion deadlock is not reachable.
const maxOpenConns = 8

// SerializeFloat32 encodes a []float32 slice into a little-endian BLOB
// compatible with sqlite-vec's expected binary embedding format.
func SerializeFloat32(v []float32) []byte {
	buf := make([]byte, len(v)*4)
	for i, f := range v {
		bits := math.Float32bits(f)
		binary.LittleEndian.PutUint32(buf[i*4:], bits)
	}
	return buf
}

// DeserializeFloat32 decodes a little-endian BLOB back into a []float32 slice.
func DeserializeFloat32(b []byte) []float32 {
	if len(b)%4 != 0 {
		return nil
	}
	result := make([]float32, len(b)/4)
	for i := range result {
		bits := binary.LittleEndian.Uint32(b[i*4:])
		result[i] = math.Float32frombits(bits)
	}
	return result
}

// Open opens (or creates) a SQLite database at the given path, enables
// WAL mode and foreign keys, and runs the full schema migration.
func Open(path string) (*sql.DB, error) {
	dsn := fmt.Sprintf("file:%s?_journal_mode=WAL&_foreign_keys=on&_busy_timeout=5000", path)
	db, err := sql.Open("sqlite3", dsn)
	if err != nil {
		return nil, fmt.Errorf("sqlite.Open: %w", err)
	}

	if err := db.Ping(); err != nil {
		db.Close()
		return nil, fmt.Errorf("sqlite.Open ping: %w", err)
	}

	db.SetMaxOpenConns(maxOpenConns)
	db.SetMaxIdleConns(maxOpenConns)

	if err := migrate(db); err != nil {
		db.Close()
		return nil, fmt.Errorf("sqlite.Open migrate: %w", err)
	}

	return db, nil
}

// migrate creates all tables, indexes, and virtual tables if they do not
// already exist. It is idempotent and safe to call on every startup.
func migrate(db *sql.DB) error {
	// CLIP dimension migration: if a model swap changes the dimension, the
	// old vec0 table must be fully rebuilt (vec0 doesn't support changing
	// dimensions). asset_clip_idx is cleared along with it; vectors are
	// regenerated by the automatic full rebuild / Embedder backfill after startup.
	if err := migrateClipDim(db); err != nil {
		return err
	}

	statements := []string{
		// ── Core asset table ──────────────────────────────────────────────
		`CREATE TABLE IF NOT EXISTS assets (
			id                   TEXT PRIMARY KEY,
			file_path            TEXT UNIQUE NOT NULL,
			file_size            INTEGER,
			mime_type            TEXT,
			original_name        TEXT,
			taken_at             DATETIME,
			duration_ms          INTEGER,
			live_photo_video_id  TEXT REFERENCES assets(id),
			is_live_photo_video  INTEGER NOT NULL DEFAULT 0,
			indexed_at           DATETIME,
			status               TEXT NOT NULL DEFAULT 'pending',
			checksum             TEXT
		)`,
		`CREATE INDEX IF NOT EXISTS idx_assets_checksum  ON assets(checksum)`,
		`CREATE INDEX IF NOT EXISTS idx_assets_taken_at  ON assets(taken_at)`,
		`CREATE INDEX IF NOT EXISTS idx_assets_status    ON assets(status)`,
		`CREATE INDEX IF NOT EXISTS idx_assets_livevideo ON assets(is_live_photo_video)`,

		// ── EXIF metadata ─────────────────────────────────────────────────
		`CREATE TABLE IF NOT EXISTS asset_exif (
			asset_id  TEXT PRIMARY KEY REFERENCES assets(id) ON DELETE CASCADE,
			width     INTEGER,
			height    INTEGER,
			latitude  REAL,
			longitude REAL,
			make      TEXT,
			model     TEXT
		)`,

		// ── Face detections ───────────────────────────────────────────────
		// excluded=1 marks a face the user removed from a person; it no longer participates in clustering/assignment/listing.
		`CREATE TABLE IF NOT EXISTS face_detections (
			id        TEXT PRIMARY KEY,
			asset_id  TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			bbox      TEXT NOT NULL,
			embedding BLOB NOT NULL,
			excluded  INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE INDEX IF NOT EXISTS idx_faces_asset ON face_detections(asset_id)`,

		// ── Persons (face clusters) ───────────────────────────────────────
		`CREATE TABLE IF NOT EXISTS persons (
			id             TEXT PRIMARY KEY,
			name           TEXT NOT NULL DEFAULT '',
			cover_asset_id TEXT REFERENCES assets(id) ON DELETE SET NULL
		)`,

		// ── Face→Person mapping ───────────────────────────────────────────
		`CREATE TABLE IF NOT EXISTS face_person (
			face_id   TEXT PRIMARY KEY REFERENCES face_detections(id) ON DELETE CASCADE,
			person_id TEXT REFERENCES persons(id) ON DELETE SET NULL
		)`,

		// ── Albums ────────────────────────────────────────────────────────
		`CREATE TABLE IF NOT EXISTS albums (
			id             TEXT PRIMARY KEY,
			name           TEXT NOT NULL,
			created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			cover_asset_id TEXT REFERENCES assets(id) ON DELETE SET NULL
		)`,

		// ── Album membership ──────────────────────────────────────────────
		`CREATE TABLE IF NOT EXISTS album_assets (
			album_id TEXT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
			asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			position INTEGER NOT NULL DEFAULT 0,
			PRIMARY KEY (album_id, asset_id)
		)`,

		// ── CLIP rowid ↔ asset_id mapping ────────────────────────────────
		`CREATE TABLE IF NOT EXISTS asset_clip_idx (
			rowid    INTEGER PRIMARY KEY,
			asset_id TEXT UNIQUE NOT NULL REFERENCES assets(id) ON DELETE CASCADE
		)`,

		// ── sqlite-vec virtual table (CLIP embeddings, dimension follows common.CLIPDim) ──
		fmt.Sprintf(`CREATE VIRTUAL TABLE IF NOT EXISTS clip_embeddings USING vec0(
			embedding float[%d]
		)`, common.CLIPDim),

		// ── Favorites (per-user, time-indexed) ────────────────────────────
		`CREATE TABLE IF NOT EXISTS asset_favorites (
			user_id      TEXT NOT NULL DEFAULT 'default',
			asset_id     TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			favorited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (user_id, asset_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_fav_user_time ON asset_favorites(user_id, favorited_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_fav_asset     ON asset_favorites(asset_id)`,

		// ── Asset views (per-user open counter) ───────────────────────────
		`CREATE TABLE IF NOT EXISTS asset_views (
			user_id        TEXT NOT NULL DEFAULT 'default',
			asset_id       TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			view_count     INTEGER NOT NULL DEFAULT 0,
			last_viewed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (user_id, asset_id)
		)`,

		// ── Merge rejections (rejected merge-suggestion pairs, (min,max) unique) ──
		`CREATE TABLE IF NOT EXISTS merge_rejections (
			person_a    TEXT NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
			person_b    TEXT NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
			rejected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (person_a, person_b),
			CHECK (person_a < person_b)
		)`,

		// ── Geo location per asset ────────────────────────────────────────────
		`CREATE TABLE IF NOT EXISTS asset_geo (
			asset_id    TEXT PRIMARY KEY REFERENCES assets(id) ON DELETE CASCADE,
			city_id     INTEGER,
			city        TEXT,
			country     TEXT,
			region      TEXT,
			admin1      TEXT,
			lat         REAL,
			lon         REAL,
			geocoded_at DATETIME
		)`,

		// ── Place cover overrides (per-user custom cover asset) ───────────────
		`CREATE TABLE IF NOT EXISTS place_cover_overrides (
			user_id   TEXT NOT NULL,
			place_key INTEGER NOT NULL,
			asset_id  TEXT NOT NULL,
			PRIMARY KEY (user_id, place_key)
		)`,

		// ── Spot name overrides (per-user custom name for an auto-detected spot) ─
		`CREATE TABLE IF NOT EXISTS spot_name_overrides (
			user_id  TEXT NOT NULL,
			spot_key TEXT NOT NULL,
			name     TEXT NOT NULL,
			PRIMARY KEY (user_id, spot_key)
		)`,

		// ── Smart Views ───────────────────────────────────────────────────────
		`CREATE TABLE IF NOT EXISTS smart_views (
			id            TEXT PRIMARY KEY,
			name          TEXT NOT NULL,
			description   TEXT,
			conds_raw     TEXT NOT NULL,
			conds_parsed  TEXT NOT NULL,
			threshold     INTEGER NOT NULL DEFAULT 70,
			live          INTEGER NOT NULL DEFAULT 1,
			include_videos INTEGER NOT NULL DEFAULT 0,
			notify_weekly INTEGER NOT NULL DEFAULT 0,
			created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			evaluated_at  DATETIME
		)`,
		`CREATE TABLE IF NOT EXISTS smart_view_matches (
			smart_view_id TEXT NOT NULL REFERENCES smart_views(id) ON DELETE CASCADE,
			asset_id      TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			match_score   REAL NOT NULL,
			matched_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (smart_view_id, asset_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_svm_sv_score ON smart_view_matches(smart_view_id, match_score)`,
		`CREATE INDEX IF NOT EXISTS idx_svm_matched  ON smart_view_matches(smart_view_id, matched_at)`,
		// ── OCR text per asset ────────────────────────────────────────────────
		// One row per OCR'd asset. text='' means "OCR ran, nothing recognized",
		// which lets the backfill distinguish done-but-empty from not-yet-done.
		// Matching uses instr(lower(text), ...) — FTS5 is not compiled into the
		// bundled mattn/go-sqlite3 build, and per-asset text is small enough
		// that a LIKE-style scan is fine at gallery scale.
		`CREATE TABLE IF NOT EXISTS asset_ocr (
			asset_id TEXT PRIMARY KEY REFERENCES assets(id) ON DELETE CASCADE,
			text     TEXT NOT NULL DEFAULT '',
			ocr_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
		)`,

		// ── OCR line geometry per asset ──────────────────────────────────────
		// One row per kept OCR line, in the same order (line_no) as the lines
		// joined into asset_ocr.text. box is the raw immich-ml quadrilateral:
		// a JSON array of 8 floats (x1,y1,…,x4,y4) normalized to [0,1] of the
		// image dimensions — resolution-independent, so the frontend can map
		// it onto any rendition. Used by GET /assets/:id/ocr (search-hit
		// highlighting); rows cascade with the asset.
		`CREATE TABLE IF NOT EXISTS asset_ocr_lines (
			asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			line_no  INTEGER NOT NULL,
			text     TEXT NOT NULL,
			box      TEXT NOT NULL DEFAULT '[]',
			score    REAL,
			PRIMARY KEY (asset_id, line_no)
		)`,

		// ── Caption backflow table (the backflow side of the photo knowledge-base sub-project) ──────────────
		// A local read-only cache of captions generated on the Parser side,
		// periodically written via diff-upsert by captionpull. mtime_ms is
		// the Parser-side version stamp, used to decide whether the old text
		// needs overwriting; fetched_at records the local write time for
		// troubleshooting. Cleaned up via ON DELETE CASCADE when the asset is
		// deleted, no extra cleanup logic needed.
		`CREATE TABLE IF NOT EXISTS asset_caption (
			asset_id   TEXT PRIMARY KEY REFERENCES assets(id) ON DELETE CASCADE,
			text       TEXT NOT NULL DEFAULT '',
			mtime_ms   INTEGER NOT NULL DEFAULT 0,
			fetched_at DATETIME
		)`,

		`CREATE TABLE IF NOT EXISTS smart_view_activity (
			id            TEXT PRIMARY KEY,
			smart_view_id TEXT NOT NULL REFERENCES smart_views(id) ON DELETE CASCADE,
			event_type    TEXT NOT NULL,
			detail        TEXT,
			asset_ids     TEXT,
			occurred_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
		)`,

		// ── Key-value metadata (e.g. index_last_rebuilt) ──────────────────────────────
		`CREATE TABLE IF NOT EXISTS photos_meta (
			key   TEXT PRIMARY KEY,
			value TEXT NOT NULL
		)`,

		// ── CLIP text-prompt embedding cache ─────────────────────────────
		// Keyed by (prompt text, MLModelGen) so a model-generation bump
		// invalidates entries automatically. Lets the OCR doc-classifier
		// score assets with pure local math — the text tower runs once per
		// prompt per generation, not per asset.
		`CREATE TABLE IF NOT EXISTS clip_text_cache (
			key TEXT NOT NULL,
			gen TEXT NOT NULL,
			vec BLOB NOT NULL,
			PRIMARY KEY (key, gen)
		)`,

		// ── Smart Moments: moment type definitions (data-driven, the vehicle for hot-updated pushes) ──────────
		`CREATE TABLE IF NOT EXISTS moment_recipes (
			key         TEXT PRIMARY KEY,          -- 'trip' / 'theme:pets' / 'theme:food' ...
			kind        TEXT NOT NULL,             -- 'trip' | 'theme' (the engine dispatches its algorithm by kind)
			title       TEXT NOT NULL,             -- English display-name template, e.g. 'Pet Moments'
			params      TEXT NOT NULL DEFAULT '{}',-- JSON: clip_prompts[]/caption_keywords[]/min_assets/max_featured/gap_days...
			enabled     INTEGER NOT NULL DEFAULT 1,
			updated_at  INTEGER NOT NULL DEFAULT 0 -- Unix ms
		)`,

		// ── Smart Moments: moment set (live entities, stable id, idempotent recompute+merge) ─────────
		`CREATE TABLE IF NOT EXISTS moments (
			id           TEXT PRIMARY KEY,         -- stable derived id (see TripMomentID/ThemeMomentID)
			recipe_key   TEXT NOT NULL,
			title        TEXT NOT NULL,            -- final display name (template base, overridden after LLM polish)
			subtitle     TEXT NOT NULL DEFAULT '', -- e.g. 'May 2011 · Yosemite'
			cover_asset_id TEXT,
			time_from    DATETIME, time_to DATETIME,
			place        TEXT NOT NULL DEFAULT '', -- trip category: primary city/country
			asset_count  INTEGER NOT NULL DEFAULT 0,
			named_by_llm INTEGER NOT NULL DEFAULT 0,
			created_at   INTEGER NOT NULL, updated_at INTEGER NOT NULL  -- Unix ms
		)`,

		// ── Smart Moments: moment members (full-replace recompute, cascade-deleted with moments) ────
		`CREATE TABLE IF NOT EXISTS moment_assets (
			moment_id  TEXT NOT NULL REFERENCES moments(id) ON DELETE CASCADE,
			asset_id   TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			featured   INTEGER NOT NULL DEFAULT 0, -- top N featured marker
			score      REAL NOT NULL DEFAULT 0,    -- in-batch ranking score (aesthetic+match-quality mix, relative meaning only)
			PRIMARY KEY (moment_id, asset_id)
		)`,

		// ── Smart Moments editable moments: pin/exclude edit records (tombstone-style replay) ──
		// moment_assets is fully replaced (delete+insert) on every recompute
		// round, so a user's manual edits to members (force-include=pin /
		// force-exclude=exclude) must be persisted independently, or they'd
		// be silently wiped by the next recompute round. SyncRecipeMoments
		// replays from this table after each round's member replacement
		// (applyMomentEdits): exclude removes -> pin re-adds; the replay
		// doesn't modify this table's contents. The composite primary key
		// (moment_id, asset_id) guarantees only the latest edit is kept per
		// asset per moment — upsert's ON CONFLICT lets a later-written op
		// overwrite an earlier one (e.g. exclude then changing your mind to
		// pin ends up as pin in effect, never both rows coexisting).
		`CREATE TABLE IF NOT EXISTS moment_edits (
			moment_id  TEXT NOT NULL REFERENCES moments(id) ON DELETE CASCADE,
			asset_id   TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			op         TEXT NOT NULL CHECK(op IN ('pin','exclude')), -- 'pin' | 'exclude'
			created_at INTEGER NOT NULL,           -- Unix ms
			PRIMARY KEY (moment_id, asset_id)
		)`,

		// ── Resumable upload task table (corresponds to Common upload.UploadTask gorm columns) ────
		`CREATE TABLE IF NOT EXISTS o_upload_tasks (
			id TEXT PRIMARY KEY,
			owner_user_id TEXT,
			filename TEXT, target_path TEXT, relative_path TEXT,
			size INTEGER, mime TEXT,
			fingerprint TEXT, content_hash TEXT,
			upload_url TEXT, uploaded_offset INTEGER DEFAULT 0,
			status TEXT, retry_count INTEGER DEFAULT 0,
			error TEXT, last_error_at INTEGER DEFAULT 0,
			batch_id TEXT, client_id TEXT, client_meta TEXT,
			created_at INTEGER DEFAULT 0, updated_at INTEGER DEFAULT 0,
			expires_at INTEGER DEFAULT 0
		)`,
		`CREATE INDEX IF NOT EXISTS idx_upload_owner   ON o_upload_tasks(owner_user_id)`,
		`CREATE INDEX IF NOT EXISTS idx_upload_status  ON o_upload_tasks(status)`,
		`CREATE INDEX IF NOT EXISTS idx_upload_expires ON o_upload_tasks(expires_at)`,

		// ── Moments M2: user profile entities (the user's own pets/family, distinct from library-wide concept moments) ──
		// Mining output is fully replaced per kind (delete all of that kind +
		// insert, idempotent), see ProfileStore.ReplaceEntities. evidence is
		// a JSON snapshot of the mining basis (photo_count/months/first/last,
		// etc.), read for troubleshooting and future upgrades (e.g. a
		// profile-confirmation interaction), not used for query filtering.
		`CREATE TABLE IF NOT EXISTS user_profile_entities (
			id          TEXT PRIMARY KEY,            -- first 16 hex chars of hash(kind|key), stable
			kind        TEXT NOT NULL,               -- 'pet' | 'person' (place/activity reserved)
			key         TEXT NOT NULL,               -- pet: species word 'beagle'; person: person_id
			label       TEXT NOT NULL DEFAULT '',    -- display name: 'Beagle' / person.name
			evidence    TEXT NOT NULL DEFAULT '{}',  -- JSON: photo_count/months/first/last, etc.
			photo_count INTEGER NOT NULL DEFAULT 0,
			first_seen  DATETIME, last_seen DATETIME,
			updated_at  INTEGER NOT NULL DEFAULT 0   -- Unix ms
		)`,
		`CREATE INDEX IF NOT EXISTS idx_profile_entities_kind ON user_profile_entities(kind)`,

		// ── Backfill failure ledger (loop-guard) ────────────────────────
		// Per-(kind, asset) exponential cooldown so a permanently failing
		// asset (corrupt file, oversized image) stops being re-selected by
		// every backfill round. Success always clears the row; the ladder
		// caps at 24h rather than blacklisting forever, so a replaced file
		// or an upgraded ML backend self-heals without manual surgery.
		`CREATE TABLE IF NOT EXISTS backfill_failures (
			kind          TEXT NOT NULL,              -- 'clip' | 'ocr' | 'sprite'
			asset_id      TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
			fail_count    INTEGER NOT NULL DEFAULT 0,
			last_fail_at  INTEGER NOT NULL DEFAULT 0, -- Unix ms
			next_retry_at INTEGER NOT NULL DEFAULT 0, -- Unix ms; > now means in cooldown
			last_error    TEXT NOT NULL DEFAULT '',
			PRIMARY KEY (kind, asset_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_backfill_failures_retry ON backfill_failures(kind, next_retry_at)`,
	}

	for _, stmt := range statements {
		if _, err := db.Exec(stmt); err != nil {
			return fmt.Errorf("migrate exec %q: %w", stmt[:min(60, len(stmt))], err)
		}
	}

	// Idempotent column expansion: extend asset_exif to hold full EXIF + video metadata.
	newCols := []struct {
		name string
		decl string
	}{
		{"iso", "INTEGER"},
		{"shutter_speed", "TEXT"},
		{"aperture", "REAL"},
		{"focal_length", "REAL"},
		{"orientation", "INTEGER"},
		{"video_codec", "TEXT"},
		{"audio_codec", "TEXT"},
		{"frame_rate", "REAL"},
		{"bit_rate", "INTEGER"},
		{"rotation", "INTEGER"},
	}

	existing := map[string]bool{}
	rows, err := db.Query(`PRAGMA table_info(asset_exif)`)
	if err != nil {
		return fmt.Errorf("migrate pragma asset_exif: %w", err)
	}
	for rows.Next() {
		var cid int
		var name, ctype string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pk); err != nil {
			rows.Close()
			return fmt.Errorf("migrate pragma scan: %w", err)
		}
		existing[name] = true
	}
	rows.Close()

	for _, col := range newCols {
		if existing[col.name] {
			continue
		}
		stmt := fmt.Sprintf("ALTER TABLE asset_exif ADD COLUMN %s %s", col.name, col.decl)
		if _, err := db.Exec(stmt); err != nil {
			return fmt.Errorf("migrate add column %s: %w", col.name, err)
		}
	}

	// Idempotent column expansion: assets.offline tracks whether the asset's
	// source file currently lives on a removable drive that's unplugged (see
	// MountGuard in service/mountguard.go). Same PRAGMA-based idempotent-add
	// pattern as the asset_exif columns above (kept separate from the
	// duplicate-column-error `alters` slice below, per design).
	assetsNewCols := []struct {
		name string
		decl string
	}{
		{"offline", "INTEGER NOT NULL DEFAULT 0"},
		// aesthetic_score: aesthetic score (NULL = not yet scored, filled in
		// by inline scoring/BackfillAesthetic; reset to NULL for rescoring on
		// a head-version change or ML generation rebuild).
		{"aesthetic_score", "REAL"},
		// mtime: the source file's ModTime().UnixNano(), written alongside
		// file_size at index time. Used by processFileInternal's "fast stat
		// skip" — on a restart-resumed scan, an asset with a matching
		// file_path+file_size+mtime and status='indexed' can be judged
		// "already processed" without reading a single byte, avoiding
		// re-streaming a hash over an entire batch of already-completed
		// large files. Rows ingested before the upgrade have this column as
		// NULL, naturally missing this fast path and falling back to the
		// checksum dedup below; mtime is backfilled in place after
		// processing once, so subsequent restarts hit the fast path.
		{"mtime", "INTEGER"},
		// caption_synced: photo knowledge-base ingestion marker — 1 = handed
		// off to Parser (caption/embedding generated for RAG retrieval), 0 =
		// not yet handed off/pending. Reset to 0 when the checksum changes
		// (content genuinely changed) or on trash restore, letting the
		// ingestion pipeline hand it off again.
		{"caption_synced", "INTEGER NOT NULL DEFAULT 0"},
	}
	assetsExisting := map[string]bool{}
	aRows, err := db.Query(`PRAGMA table_info(assets)`)
	if err != nil {
		return fmt.Errorf("migrate pragma assets: %w", err)
	}
	for aRows.Next() {
		var cid int
		var name, ctype string
		var notnull, pk int
		var dflt sql.NullString
		if err := aRows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pk); err != nil {
			aRows.Close()
			return fmt.Errorf("migrate pragma scan assets: %w", err)
		}
		assetsExisting[name] = true
	}
	aRows.Close()
	for _, col := range assetsNewCols {
		if assetsExisting[col.name] {
			continue
		}
		stmt := fmt.Sprintf("ALTER TABLE assets ADD COLUMN %s %s", col.name, col.decl)
		if _, err := db.Exec(stmt); err != nil {
			return fmt.Errorf("migrate add column assets.%s: %w", col.name, err)
		}
	}
	// No index on assets.offline: it's a low-cardinality boolean, and its
	// consumers filter by prefix UPDATE/SELECT where the planner wouldn't use
	// it anyway. DROP cleans up any DB migrated by an intermediate build that
	// briefly created one.
	if _, err := db.Exec(`DROP INDEX IF EXISTS idx_assets_offline`); err != nil {
		return fmt.Errorf("migrate drop index assets_offline: %w", err)
	}

	// ── assets.face_scanned: marker column for the standalone face-detection task (RunPipeline) ──────
	// An asset with no row in face_detections != never detected (the
	// detection pass may genuinely have found no face). An explicit marker
	// column distinguishes "already scanned" from "pending scan", used by
	// RunPipeline to scope the pending set
	// (status='indexed' AND offline=0 AND face_scanned=0). Only the first
	// time this column is added, within the same transaction, mark all
	// currently indexed existing assets as already scanned in one shot, to
	// avoid triggering a sudden library-wide rescan after the upgrade
	// (existing assets missed during a historical ML outage are not
	// automatically backfilled — consistent with the status quo, see the
	// spec's "tradeoffs" section).
	var faceScannedExisting bool
	fsRows, err := db.Query(`PRAGMA table_info(assets)`)
	if err != nil {
		return fmt.Errorf("migrate pragma assets face_scanned: %w", err)
	}
	for fsRows.Next() {
		var cid int
		var name, ctype string
		var notnull, pk int
		var dflt sql.NullString
		if err := fsRows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pk); err != nil {
			fsRows.Close()
			return fmt.Errorf("migrate pragma scan assets face_scanned: %w", err)
		}
		if name == "face_scanned" {
			faceScannedExisting = true
		}
	}
	fsRows.Close()
	if !faceScannedExisting {
		tx, err := db.Begin()
		if err != nil {
			return fmt.Errorf("migrate face_scanned begin: %w", err)
		}
		if _, err := tx.Exec(`ALTER TABLE assets ADD COLUMN face_scanned INTEGER NOT NULL DEFAULT 0`); err != nil {
			tx.Rollback()
			return fmt.Errorf("migrate add column assets.face_scanned: %w", err)
		}
		if _, err := tx.Exec(`UPDATE assets SET face_scanned=1 WHERE status='indexed'`); err != nil {
			tx.Rollback()
			return fmt.Errorf("migrate backfill assets.face_scanned: %w", err)
		}
		if err := tx.Commit(); err != nil {
			return fmt.Errorf("migrate face_scanned commit: %w", err)
		}
	}

	// ── Idempotent column migration: legacy DBs created with CREATE TABLE IF NOT EXISTS
	//    won't have new columns; ALTER TABLE ADD COLUMN fills them in.
	//    SQLite raises "duplicate column" when the column already exists — ignore it.
	alters := []string{
		`ALTER TABLE assets ADD COLUMN deleted_at DATETIME`,
		`ALTER TABLE assets ADD COLUMN original_path TEXT`,
		`ALTER TABLE persons ADD COLUMN cover_face_id TEXT`,
		`ALTER TABLE persons ADD COLUMN favorite INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE persons ADD COLUMN relation TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE persons ADD COLUMN hidden INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE persons ADD COLUMN confidence REAL NOT NULL DEFAULT 0`,
		`ALTER TABLE persons ADD COLUMN centroid BLOB`,
		`ALTER TABLE persons ADD COLUMN created_at DATETIME`,
		`ALTER TABLE persons ADD COLUMN updated_at DATETIME`,
		`ALTER TABLE album_assets ADD COLUMN position INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE face_detections ADD COLUMN excluded INTEGER NOT NULL DEFAULT 0`,
		// OCR document-ness signals: coverage = text-box area / image area in
		// [0,1] (NULL until the OCR backfill recomputes it from box geometry);
		// line_count = recognized lines kept after the confidence filter.
		`ALTER TABLE asset_ocr ADD COLUMN coverage REAL`,
		`ALTER TABLE asset_ocr ADD COLUMN line_count INTEGER`,
		// cover_locked=1 means the user has pinned a specific cover face; auto-recompute skips cover update.
		`ALTER TABLE persons ADD COLUMN cover_locked INTEGER NOT NULL DEFAULT 0`,
		// hero_asset_id: user-chosen hero/background photo for this person (must have a valid face).
		`ALTER TABLE persons ADD COLUMN hero_asset_id TEXT`,
		// boxes_ver=0 → OCR text predates line-geometry storage; the OCR
		// backfill (queryMissingOCR) re-runs these to populate asset_ocr_lines.
		`ALTER TABLE asset_ocr ADD COLUMN boxes_ver INTEGER NOT NULL DEFAULT 0`,
		// OCR doc-classifier hybrid verdict (see docs: density gate + CLIP
		// zero-shot margin + line-geometry regularity). is_doc NULL = not yet
		// scored (queries fall back to the legacy density rule); doc_ver=0
		// marks rows for the pure-math backfill.
		`ALTER TABLE asset_ocr ADD COLUMN doc_sem REAL`,
		`ALTER TABLE asset_ocr ADD COLUMN doc_geo REAL`,
		`ALTER TABLE asset_ocr ADD COLUMN is_doc INTEGER`,
		`ALTER TABLE asset_ocr ADD COLUMN doc_ver INTEGER NOT NULL DEFAULT 0`,
		// smart_view_matches.origin: row origin (0=auto match/1=manual
		// pin/2=manual exclude). Pinned rows are never deleted by
		// re-evaluation and keep a score of 1.0; excluded rows are retained
		// as "memory", filtered out of read paths via origin<>2.
		`ALTER TABLE smart_view_matches ADD COLUMN origin INTEGER NOT NULL DEFAULT 0`,
		// moments.sort_order: Moments drag-to-reorder manual sort (NULL=not
		// manually sorted; see momentstore.go for ListMoments' sort
		// semantics). PUT /v1/photos/moments/order writes (i+1)*10 (leaving
		// gaps for future inserts); SyncRecipeMoments' upsert column list
		// excludes this column, so recompute naturally preserves the user's manual order.
		`ALTER TABLE moments ADD COLUMN sort_order INTEGER`,
		// moments.hidden: tombstone for the user "hiding this moment"
		// (0=shown normally, 1=hidden). ListMoments filters by hidden=0;
		// SyncRecipeMoments' upsert column list likewise excludes this
		// column (same approach as sort_order/named_by_llm), so recompute
		// naturally preserves the hidden state.
		`ALTER TABLE moments ADD COLUMN hidden INTEGER NOT NULL DEFAULT 0`,
		// moment_assets.manual: marks whether this member row was inserted
		// via a user pin-edit replay (1=manually added by the user, not
		// produced by this engine round; 0=normally produced by this engine
		// round). Only for display/troubleshooting to distinguish origin,
		// not part of SyncRecipeMoments' replacement logic itself.
		`ALTER TABLE moment_assets ADD COLUMN manual INTEGER NOT NULL DEFAULT 0`,
		// moment_assets.added_at: timestamp (Unix ms) when the member joined
		// the moment. NULL = existing/join time unknown (rows that existed
		// before the upgrade; excluded from the "added this week" count, to
		// avoid the whole library showing +N in the first week after
		// launch). SyncRecipeMoments' member sync has switched to a diff-
		// style upsert (see momentstore.go comments): newly inserted members
		// get the current timestamp, and the conflict branch for existing
		// members doesn't touch this column.
		`ALTER TABLE moment_assets ADD COLUMN added_at INTEGER`,
	}
	for _, stmt := range alters {
		if _, err := db.Exec(stmt); err != nil &&
			!strings.Contains(err.Error(), "duplicate column") {
			return fmt.Errorf("migrate alter: %w", err)
		}
	}
	if _, err := db.Exec(`CREATE INDEX IF NOT EXISTS idx_assets_deleted_at ON assets(deleted_at)`); err != nil {
		return fmt.Errorf("migrate index deleted_at: %w", err)
	}

	// Derive line_count for legacy asset_ocr rows from the stored text so the
	// OCR-category line threshold applies immediately, before the coverage
	// re-OCR backfill reaches them. Idempotent: only fills NULLs.
	if _, err := db.Exec(`
		UPDATE asset_ocr SET line_count = CASE
			WHEN text = '' THEN 0
			ELSE length(text) - length(replace(text, char(10), '')) + 1
		END
		WHERE line_count IS NULL`); err != nil {
		return fmt.Errorf("migrate backfill asset_ocr.line_count: %w", err)
	}

	if _, err := db.Exec(`CREATE INDEX IF NOT EXISTS idx_album_assets_position ON album_assets(album_id, position)`); err != nil {
		return fmt.Errorf("migrate index album_assets_position: %w", err)
	}

	if _, err := db.Exec(`CREATE INDEX IF NOT EXISTS idx_asset_geo_city ON asset_geo(city_id)`); err != nil {
		return fmt.Errorf("migrate index asset_geo_city: %w", err)
	}

	// Backfill position: only runs when an album has >=2 rows all at position=0,
	// which distinguishes legacy unbackfilled rows from a freshly-created album.
	// Idempotent: after backfill MAX(position) > 0, so HAVING never fires again.
	// NOTE: AddAsset/ReorderAssets now write distinct positions, so any album
	// where MAX(position) > 0 is treated as already backfilled. The HAVING guard
	// remains as a safety net for legacy DBs and is harmless on re-run.
	if _, err := db.Exec(`
		WITH targets AS (
			SELECT album_id FROM album_assets
			GROUP BY album_id
			HAVING COUNT(*) >= 2 AND MIN(position) = 0 AND MAX(position) = 0
		),
		ordered AS (
			SELECT album_id, asset_id,
			       ROW_NUMBER() OVER (PARTITION BY album_id ORDER BY added_at, asset_id) - 1 AS pos
			FROM album_assets WHERE album_id IN (SELECT album_id FROM targets)
		)
		UPDATE album_assets SET position = (
			SELECT pos FROM ordered o
			WHERE o.album_id = album_assets.album_id AND o.asset_id = album_assets.asset_id
		)
		WHERE album_id IN (SELECT album_id FROM targets)
	`); err != nil {
		return fmt.Errorf("migrate backfill album_assets.position: %w", err)
	}

	if err := regeocodeIfStale(db); err != nil {
		return err
	}

	// Timeline sort/bucket indexes. Every list surface orders by
	// COALESCE(taken_at, indexed_at) DESC; a plain column index cannot
	// serve an expression sort, so without these every page request
	// re-sorts the whole live set. Partial WHERE mirrors the shared
	// timeline filters exactly — queries must repeat those three
	// predicates verbatim for the planner to accept the partial index.
	// strftime with an explicit format (no 'now'/'localtime') is
	// deterministic and therefore legal in an index expression.
	for _, stmt := range []string{
		`CREATE INDEX IF NOT EXISTS idx_assets_sortkey
		   ON assets(COALESCE(taken_at, indexed_at) DESC)
		   WHERE deleted_at IS NULL AND offline = 0 AND is_live_photo_video = 0`,
		`CREATE INDEX IF NOT EXISTS idx_assets_monthkey
		   ON assets(strftime('%Y-%m', COALESCE(taken_at, indexed_at)),
		             COALESCE(taken_at, indexed_at) DESC)
		   WHERE deleted_at IS NULL AND offline = 0 AND is_live_photo_video = 0`,
	} {
		if _, err := db.Exec(stmt); err != nil {
			return fmt.Errorf("timeline index: %w", err)
		}
	}

	// Without sqlite_stat1, SQLite's cost model defaults to a fixed guess
	// for equality-constrained indexes and ends up preferring
	// idx_assets_livevideo (is_live_photo_video is almost always 0, so that
	// "search" touches nearly every row) plus a temp b-tree sort, instead of
	// walking idx_assets_sortkey directly — silently defeating the indexes
	// just added above. Scoping ANALYZE to the assets table keeps this cheap
	// even on large libraries (it does not scan every other table).
	if _, err := db.Exec(`ANALYZE assets`); err != nil {
		return fmt.Errorf("migrate analyze assets: %w", err)
	}

	return nil
}

var clipDimRe = regexp.MustCompile(`float\[(\d+)\]`)

// clipDimMatches precisely parses the vector dimension out of the DDL before
// comparing. A previous version used strings.Contains(ddl, "float[N]")
// substring matching, which misjudged "already correct" and skipped a
// necessary rebuild whenever the target dimension was a prefix of the
// existing dimension (e.g. 115 vs 1152).
func clipDimMatches(ddl string, dim int) bool {
	m := clipDimRe.FindStringSubmatch(ddl)
	if m == nil {
		return false
	}
	got, err := strconv.Atoi(m[1])
	return err == nil && got == dim
}

// migrateClipDim checks whether the existing clip_embeddings table's
// dimension equals common.CLIPDim; if not, DROPs it (its vec0 shadow tables
// go with it) and clears asset_clip_idx. A no-op if the table doesn't exist.
func migrateClipDim(db *sql.DB) error {
	var ddl string
	err := db.QueryRow(`SELECT sql FROM sqlite_master WHERE type='table' AND name='clip_embeddings'`).Scan(&ddl)
	if err == sql.ErrNoRows {
		return nil // new DB, follows the normal table-creation path
	}
	if err != nil {
		return fmt.Errorf("migrateClipDim read ddl: %w", err)
	}
	if clipDimMatches(ddl, common.CLIPDim) {
		return nil // dimension is already correct
	}
	if _, err := db.Exec(`DROP TABLE clip_embeddings`); err != nil {
		return fmt.Errorf("migrateClipDim drop: %w", err)
	}
	if _, err := db.Exec(`DELETE FROM asset_clip_idx`); err != nil {
		// asset_clip_idx may not have been created yet (a very old DB); ignore no such table
		if !strings.Contains(err.Error(), "no such table") {
			return fmt.Errorf("migrateClipDim clear idx: %w", err)
		}
	}
	return nil
}

// geoGazVersion is bumped whenever the embedded gazetteer or the reverse-geocode
// algorithm changes in a way that alters which city a coordinate resolves to.
// v1: metro-snap + coarser gazetteer (drop PPLX & capital-swallowed sub-divisions),
//
//	so dense metros (e.g. Hong Kong, Macau) resolve to one city instead of many.
const geoGazVersion = 1

// regeocodeIfStale clears asset_geo when the gazetteer version stored in the DB
// is older than geoGazVersion, so the GeoService scheduler re-geocodes every
// asset against the current gazetteer. asset_geo is fully derived from
// asset_exif lat/lon, so clearing it is safe and self-healing.
func regeocodeIfStale(db *sql.DB) error {
	var stored int
	if err := db.QueryRow(`PRAGMA user_version`).Scan(&stored); err != nil {
		return fmt.Errorf("migrate read user_version: %w", err)
	}
	if stored >= geoGazVersion {
		return nil
	}
	if _, err := db.Exec(`DELETE FROM asset_geo`); err != nil {
		return fmt.Errorf("migrate clear asset_geo for re-geocode: %w", err)
	}
	// PRAGMA user_version does not accept a bound parameter.
	if _, err := db.Exec(fmt.Sprintf(`PRAGMA user_version = %d`, geoGazVersion)); err != nil {
		return fmt.Errorf("migrate set user_version: %w", err)
	}
	return nil
}
